version: '3.3'

services:
  database:
    image: 'postgres:15.4'
    ports:
      - 5432:5432
    env_file:
      - ./postgreSQL/.env
    volumes:
      - ./postgreSQL/postgres-data/:/var/lib/postgresql/data/


  nats:
      image: 'nats:2.9.21'
      ports:
        - "4222:4222"
        - "8222:8222"
        - "6222:6222"
      hostname: nats-server


  frontend:
      image `frontend